### ISSUE TITLE
[오류 개선] 홈페이지 접속 시 번들 컴파일이 잘 안되는 현상 발생

### ISSUE THREAD

**Issue by rjs1197** [JuniorDevelopersKR/Athena#26]
현상은 다음과 같습니다.

![plzhp](https://user-images.githubusercontent.com/24822072/46567963-4410a480-c978-11e8-9af4-9624be8aa585.gif)

이 부분에 대해 해결이 필요해요

**Comment by rjs1197** [comment]
module.js:549
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './.db_config'
[0]     at Function.Module._resolveFilename (module.js:547:15)
[0]     at Function.Module._load (module.js:474:25)
[0]     at Module.require (module.js:596:17)
[0]     at require (internal/module.js:11:18)
[0]     at /Users/rayleigh/Development/Athena/src/server/db/db_connect.js:5:16
[0]     at Object.<anonymous> (/Users/rayleigh/Development/Athena/src/server/db/db_connect.js:21:2)
[0]     at Module._compile (module.js:652:30)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
error Command failed.

아마 이 부분이 문제일 것 같은데, 이건  db_config에 대한 문제이기 때문에 이를 해결하기 위해서는 이 부분에 대한 파일을 따로 전달받아야 할 것 같습니다
